#
# Settings
# 

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/ayu.toml"
]

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "F11"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
#decorations = "Buttonless"
startup_mode = "SimpleFullscreen"
dynamic_padding = true
padding = {x = 8, y = 4}


#
# Fonts
#

[font]
size = 14
normal = { family = "CommitMono", style = "Regular" }
glyph_offset = {y = 1}

# FixederSys
#size = 16
#normal = { family = "FixederSys Light 2x"}
#glyph_offset = {y = 0}
#offset = {y = -3}

